name: "Rpi5 OS Build"
on:
  workflow_dispatch:

jobs:
  buildOS:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        token: '${{ secrets.ACTION_GITHUB_TOKEN }}'
    - run: sudo apt-get install -y qemu-user-static
    - name: Install nix
      uses: cachix/install-nix-action@master
      with:
        github_access_token: '${{ secrets.ACTION_GITHUB_TOKEN }}'
        extra_nix_config: |
          system = aarch64-linux
    - name: Import GPG key
      id: import-gpg
      uses: crazy-max/ghaction-import-gpg@master
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        git_user_signingkey: true
        git_commit_gpgsign: true
    - name: Configure git credentials
      run: |
        git config --global user.email "${{ steps.import-gpg.outputs.email }}"
        git config --global user.name "${{ steps.import-gpg.outputs.name }}"
    - name: Setup cachix
      uses: cachix/cachix-action@master
      with:
        name: antares0982
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: nix build
      run: |
        nix build -L .#nixosConfigurations.rpi5.config.system.build.toplevel --show-trace
